---
- name: Install mariadb, MySQL-python
  yum:  
    name:
      - mariadb-server 
      - mariadb
      - MySQL-python
      - python2-PyMySQL
   
    state: present
  notify: Start_Mariadb
  
- name: Start and enable MySQL
  service:
    name: mariadb
    state: started
    enabled: yes  

- name: Creating a database in mariadb
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}" 
    login_host: localhost

- name: Creating a database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
  no_log: True  

