---
- name: Install Apache on webservers
  yum:
    name: httpd
    state: present 
  notify: Start Apache
    
- name: Install Git
  yum:
    name: git
    state: present

- name: Clone the repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ web_app_dir }}"
    version: master
    force: yes
    update: yes

- name: Set permissions for web application directory
  file:
    path: "{{ web_app_dir }}"
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes